# Generated by Django 5.1.1 on 2024-10-07 09:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
