# Generated by Django 5.1.1 on 2024-10-07 09:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpitch', '0002_blogpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='short',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
