# Generated by Django 5.1.1 on 2024-10-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpitch', '0003_blogtagindexpage'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTagIndexPage',
            new_name='BlogPageWithTag',
        ),
    ]
